language: ruby
rvm:
- 2.3.1
addons:
  postgresql: '9.3'
  code_climate:
    repo_token: <%= ENV["CODECLIMATE_REPO_TOKEN"] %>
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
- cp config/secrets.yml.travis config/secrets.yml
- cp config/initializers/secret_token.rb.travis config/initializers/secret_token.rb
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- bundle exec rake db:test:prepare
- bundle exec codeclimate-test-reporter
- bundle exec rspec spec/
env:
  global:
  - secure: pvCRamOmY8XAWXYE+QjgjxCIvvN4nJvZ8pm++gwltWS/H+pj6OhzD+uplXGzCIfa+wElzuXMIajJX+NANqmnfUg5RvPJ0HijYM9DMWXwM5+rzJUT69ntpHd81J5FzMbGrE+tjem/hC3FEIF/idybb/7fD0CgCcIHa0DewqDhQeHXajPK9UkJ/+gb9WoKYV4OQgH4SAG5L8l8fwavF4BA+/xWuzu1NZ8DhI8h2hdKPhE5sv8Vj1FO/N7Fr6o9RPInPGD7CYXYOCglFLqlVsQ67V+EnckGyz4dCYM01Ov3XAu+szn8dOqKBBLG7yPUokfqivJnwDlsKoAskx62EcouttgdcPa9di902Y7dt6q3DG32p+d1dpb2+LspNkfC3al88kVvq21+LrxMxmDiXJzvSVtDr4FgV+AJdYub7GYFDm+tFXZE0Ls7R/GC/HFNzuR7WTOsdDxptKmiIQLGfm7Xs80pyJGqY527iPz5qlyq3/CF45YY7yuM7Nl3zt076Po0K+5HOOPTC3jMzOAsgjuvAAMzZzc8f/kNP0h/sznjR0+ea2aV2sBQpYnUuPDBUfgC+x6KVud5UUa4uU9LijKbGJvcQOGCGDgyf6yn7FOM9xGOL8HYcqEexUT8HUYHQADZueN7xNwD3IgGoY45PLhwSvlCiMRWy6AIOjEdibZMX4Y=
  - secure: t4QTf3E40VEjft9ACLRvbKYhncRIh/yA+voHo23Vgq+kuPx0R+CdsHTyiJZcVI1Ki4wRXpfcuFl4lMjW/0fmwasb9J/8XjOrEbhA5k+EWP/KiRA8akRkEWiHSaXvAuk8qx6R1zHIuQ370mnW0K1G4vW3XuqR5PBe8mGv8nLq6f0r9z3khi+MERuzbe4ptHtytEzy4JKDjTeTDQFJTEWVRQ0A0OotocV1cih0Uk04g0IIBBTSQQVZvRgJTJSc8UnL7HqvF5Riq8chGra9rkmM8Rfj+wweAEUOscs8EWYgL6L2YJf2H+MteGwXvSa0gL+pRx+xMkGjYj/+iiYkTttPyPNRGYyLNB/3X5qipuQB0zdHydUq5jX3IKChQ19oSTwxu4+nLVo9EeZ8+1twfMdDibSlmlZeKpzd7oWWmk636iNK2zqs6FlvS/skgUfIIm3DyWSJRtl2v6N9QSzF/KFdXFcohsUoIkP4Y/DriEzWel8n7Kn6yYjmltGIu6nLBWXzGj1mD9l/SGfUU9tC1L+D8fOJA95zpMm/rA4L3UJL43xmFAv1rhWkHEjYDrVjZzZWsVt2kQADb768BqoFLrqSnK6MvCb4s7pV9blPNizWoME89DI/dprfkRKGfhZP1bGJ2DFJ2jW5uT0iDCncR7zTKyWSMetqx2KNAI0NbAusDGA=
  matrix:
    secure: xmsvNqTtWpSIUDaPAKjTCf2E9kM/DAOLv26Wswh+/+TQKsX/8kli4PkM8REHAHSURD/oOpDZeW9k12BQD2a4MRw/umun8D9mwHwryacFjUwV52qx0GvJYNNeuwM9XlDH0QSUizo8YK9zfBLAsyC4fAoaAsi4a+2bDnOzn18IZA7ScsrDlm7EUan3Dk0unpvz6tpMo7D8kvUiuwkkfy7UdhH/uR9rn//jeSVngZJzuc51uq8+Pc6LXT0hG3QgrSTXySNYvhrfmCiHNLa2Vrini1xpUldsRTZKfPPTOu0EzghjcquTzcsHxmNZmcwNRnYPEbOf/Qjky+Aien2fkw+kNsKPZkI9+I5Hvd5G+YG/H8F2HJVsp2CvxJ7gPz4fWK+IW+EtgLEWt0zFrHHdGLM3CMg0MtHxL53LXjHoJxIlgJtmDwKdW8YkBjfZ6JcVmOzToZb5je56VdNaW39tYsjdmRgD1HoPPVpqbaEKtk+0gjASAjpzgeaAuxj9iU3vCa2jpPnE1FfDR8gy65soFWdmwcLMWvEzNpQzhi0QLVpkV/803ksIhttTt/5ZpnwZ2/DmY/9vNyV7hZYeUJaDYiY9/K9/MNxe+GjzrxBCUGUTVVo/00odz0qR+GKU8YxnW7PwSSC/UKCdQzPJ+V/hWnUFL1IIO46sJ1GLhB5C74YiX70=
